name: WakaTime Status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      # 第一步：更新全量统计 (All Time)
      - name: Update All Time Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka
          TIME_RANGE: all_time
          SHOW_TITLE: true
          BLOCKS: ->
          LANG_COUNT: 5

      # 第二步：更新周统计 (Last 7 Days)
      - name: Update Weekly Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: weekly
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          LANG_COUNT: 5
